### ISSUE TITLE
Problem with sphere_lattice when the dimension is high

### ISSUE THREAD

**Issue by wanliAlex** [erikbrinkman/fibonacci_lattice#1]
Hi, when the dimension is high (600 in my case), there is an error:

mults = [gamma(d / 2 + 0.5) / gamma(d / 2) / sqrt(pi) for d in range(2, dim)]
OverflowError: math range error

**Comment by wanliAlex** [comment]
One possible solution is to change gamma to lgamma and exp() it.

**Comment by erikbrinkman** [comment]
Yeah, using log space is more numerically stable, so this seemed to work, however, this is super slow with dimension set to 600. There are other ways to get around this, but it will require a dependency, so it'll take a little more effort :/

**Comment by wanliAlex** [comment]
Yes, it will take longer to generate the code. Luckily I only need to generate the code once and save it as a NumPy file. Thanks for the update.

**Comment by erikbrinkman** [comment]
I managed to update the inner part of the loop with numba in 0.2.0, and switched the entire thing to numpy in 0.3 which probably made it a bit faster, so those also might help.
